#!/usr/bin/env bash

local os=$(uname)

if [ $os = "Darwin" ] || ! grep -i "nixos" /etc/os-release 2>&1 > /dev/null; then
    # Install and set up Lix on MacOS. Once the installer is done, nix command will be available
    # and we can run `nix run nix-darwin -- switch --flake <host>`
    curl -sSf -L https://install.lix.systems/lix | sh -s -- install
else
    # Install configuration files for nix command. Enable experimental features like nix command
    # and flakes. Then we can run commands to either switch or install NixOS itself
    mkdir -p ~/.config/nix
    sudo mkdir -p /root/.config/nix
    echo "experimental-features = nix-command flakes" > ~/.config/nix/nix.conf
    echo "experimental-features = nix-command flakes" | sudo tee /root/.config/nix/nix.conf 2>&1 > /dev/null
fi
