#!/usr/bin/env bash

mkdir -p ~/.config/nix
sudo mkdir -p /root/.config/nix

echo "experimental-features = nix-command flakes" > ~/.config/nix/nix.conf
echo "experimental-features = nix-command flakes" | sudo tee /root/.config/nix/nix.conf 2>&1 > /dev/null

sudo nix run .#os-install -- "$1"
